---

- name: Installation of specific Webserver
  hosts: all
  tasks:
  vars:
    webserver_suse: apache2
    webserver_ubuntu: apache2
    webserver_centos: httpd

    webserver:
      Debian: apache2

  tasks:
  - name: Install if CentOS
    package:
      name: "{{webserver_centos}}"
      state: present
    when: ansible_distribution == "CentOS"
# ansible_distribution | ansible_distribution_file_variety -> same, verschiedene commands gleicher Output

#  - name: Install if SUSE
#    package: 
#      name: {{webserver_suse}}
#      state: present
#    when: ansible_distribution == "openSUSE Leap"

  - name: Install if Debian
    package:
      name: "{{webserver[ansible_os_family]}}"
      state: present
      when: ansible_os_family == "Debian"
