---

- name: My first Template Playbook
  hosts: all

  tasks:
  - include_vars: "{{ ansible_os_family }}.yml"

  - name: ensure that the "{{ apache2_package_state }}" version of the apache2 is there
    package: 
      name: "{{ apach2_package }}"
      state: "{{ apache2_package_state }}"
    notify:
      - Start apache2
